const SUCCESS = 1
const ACTIVE = 2
const PURCHASE_WAIT = 1
const PURCHASE_OK = 2
const PURCHASE_CANCEL = 3
const SALE_CUSTOMER_BUSINESS = 1
const SALE_CUSTOMER_OTHER = 2
const STOCK_REASON_PURCHASE = 1
const STOCK_REASON_SALE = 2
const AUTH_ERROR = -8

export const StatusCode = {
  SUCCESS,
  ACTIVE,
  PURCHASE_WAIT,
  PURCHASE_OK,
  PURCHASE_CANCEL,
  SALE_CUSTOMER_BUSINESS,
  SALE_CUSTOMER_OTHER,
  STOCK_REASON_PURCHASE,
  STOCK_REASON_SALE,
  AUTH_ERROR,
}
